{{- $labels := include "chef-ingest.labels" .}}

{{- if .Values.secrets.ingredients }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "secret-ingredients"
  labels: {{ $labels | nindent 4 }}
data:
  {{- range $key, $value := .Values.secrets.ingredients }}
  {{- if not ($value | empty) }}
  {{  $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}

---
{{- end }}


{{- if (.Values.secrets.sink.dataHubSink | trim | empty) }}
  {{- required "dataHubSink must not be an empty string" .Values.secrets.sink.dataHubSink }}
{{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "secret-sink"
  labels: {{ $labels | nindent  4}}
data:
  {{- range $key, $value := .Values.secrets.sink }}
  {{- if not ($value | empty) }}
  {{  $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}

---
